name: 'Delete old releases'
on:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    steps: 
      - run: ls
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0 
          delete_tags: true 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
